kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: upload-demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: upload-demo
    spec:
      containers:
      - name: demo
        image: us-ashburn-1.ocir.io/unifor/celula09/demo-springboot:latest
        ports:
        - name: upload-demo
          containerPort: 8080
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME