kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: us-ashburn-1.ocir.io/unifor/celula09/demo-springboot:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME