kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: upload-demo-${TARGET_ROLE}
spec:
  replicas: 2
  template:
    metadata:
      name: upload-demo
      labels:
        app: upload-demo
        role: {TARGET_ROLE}
    spec:
      containers:
      - name: demo
        image: demo:${BUILD_NUMBER}
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        ports:
        - name: upload-demo
          containerPort: 8080