kind: Deployment
apiVersion: apps/v1
metadata:
  labels: 
    run: upload-springboot
  name: upload-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      run: upload-springboot
  template:
    metadata:
      labels:
        run: upload-springboot
    spec:
      containers:
      - name: upload-springboot
        image: us-ashburn-1.ocir.io/unifor/celula09/demo-springboot:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME