kind: Service
apiVersion: v1
metadata:
  labels: 
    run: upload-springboot
  name: upload-springboot
spec:
  type: LoadBalancer
  selector:
    matchLabels:
      run: upload-springboot
  ports:
    - port: 80
      targetPort: 8080