kind: Service
apiVersion: v1
metadata:
  name: upload-demo
  labels:
    role: ${TARGET_ROLE}
    env: production
spec:
  type: LoadBalancer
  selector:
    app: tomcat
    role: ${TARGET_ROLE}
  ports:
    - port: 80
      targetPort: 8080